global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  # Labels attached to all time series collected by Prometheus
  external_labels:
    monitor: 'ai-call-secretary-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alertmanager service will be configured in the future
          # - alertmanager:9093

# Rules for alerting
rule_files:
  # Alerting rules will be configured in the future
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API service
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # NGINX
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'ai-call-secretary'